# Generated by Django 3.2.3 on 2021-06-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_alter_rate_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
