# Generated by Django 3.2.3 on 2021-06-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0020_auto_20210602_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
